export const records = [
  {
    id: 'intro',
    label: 'Introduction',
    shortLabel: 'INTRO',
    rpm: '33⅓',
    color: '#C4783A',
    labelBg: 'radial-gradient(circle at 40% 35%, #D4885A, #8B4513)',
    textColor: '#F5ECD7',
  },
  {
    id: 'publications',
    label: 'Publications',
    shortLabel: 'PUB',
    rpm: '33⅓',
    color: '#4A6741',
    labelBg: 'radial-gradient(circle at 40% 35%, #5A7751, #2E4A28)',
    textColor: '#D4EBC8',
  },
  {
    id: 'projects',
    label: 'Projects',
    shortLabel: 'PROJ',
    rpm: '45',
    color: '#5A4A7A',
    labelBg: 'radial-gradient(circle at 40% 35%, #6A5A8A, #3A2A5A)',
    textColor: '#E8DEFF',
  },
  {
    id: 'writing',
    label: 'Writing',
    shortLabel: 'WRITE',
    rpm: '33⅓',
    color: '#7A4A3A',
    labelBg: 'radial-gradient(circle at 40% 35%, #8A5A4A, #4A2A1A)',
    textColor: '#FFE8D8',
  },
  {
    id: 'resume',
    label: 'Résumé',
    shortLabel: 'CV',
    rpm: '45',
    color: '#4A5A6A',
    labelBg: 'radial-gradient(circle at 40% 35%, #5A7080, #2A3A4A)',
    textColor: '#D8F0FF',
  },
  {
    id: 'contact',
    label: 'Contact',
    shortLabel: 'CONTACT',
    rpm: '33⅓',
    color: '#6A5A3A',
    labelBg: 'radial-gradient(circle at 40% 35%, #7A6A4A, #4A3A1A)',
    textColor: '#FFF0C8',
  },
]
